---
name: Update branch
on:
  workflow_call:
    inputs:
      body:
        required: false
        type: string
        default: "/ub"
    secrets:
      gh_token:
        required: false
      gh_app_id:
        required: false
      gh_app_private_key:
        required: false

permissions: {}

jobs:
  update-branch:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_comment-use-issue_comment
    timeout-minutes: 30
    if: github.event.issue.pull_request && github.event.comment.body == inputs.body
    runs-on: ubuntu-latest
    steps:
      # secrets.GITHUB_TOKEN can't be used because it can't trigger GitHub Actions Workflow
      # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow
      # > When you use the repository's GITHUB_TOKEN to perform tasks, events triggered by the GITHUB_TOKEN will not create a new workflow run
      - uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
        id: token
        with:
          github_token: ${{secrets.gh_token}}
          github_app_id: ${{secrets.gh_app_id}}
          github_app_private_key: ${{secrets.gh_app_private_key}}

      # https://cli.github.com/manual/gh_api
      # https://docs.github.com/en/rest/reference/pulls#update-a-pull-request-branch
      - run: gh api -X PUT "repos/${GITHUB_REPOSITORY}/pulls/${PR_NUMBER}/update-branch"
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          PR_NUMBER: ${{ github.event.issue.number }}
